version: 2
jobs:
    # The build job
    build:
        working_directory: ~/project
        docker:
            - image: circleci/node:latest
        steps:
            # Checkout the code from the branch into the working_directory
            - checkout
            # Log the current branch
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            # Restore local dependencies from cache
            - restore_cache:
                keys:
                - v2-dependencies-{{ checksum "package.json" }}
                - v2-dependencies-
            # Install project dependencies
            - run:
                name: Install local dependencies
                command: npm install && npm install @angular/compiler-cli
            - run:
                name: rebuild nodesass
                command: npm rebuild node-sass
            # Cache local dependencies if they don't exist
            - save_cache:
                key: v2-dependencies-{{ checksum "package.json" }}
                paths:
                    - node_modules
            # Lint the source code
            #- run:
            #    name: Linting
            #    command: npm run lint
            # Test the source code
            #- run:
            #    name: Testing
            #    command: npm run test
            # Build project with different configuration based on
            # the current branch
            - run:
                name: Building
                command: npm run build-prod
            # Cache the docs folder for the deploy job
            - save_cache:
                key: v2-docs-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
                paths:
                    - docs

    # The deploy job
    deploy:
        working_directory: ~/project
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            # Log the current branch
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            # Restore cache from the build job which contains the
            # dist folder that needs to be deployed
            - restore_cache:
                key: v2-docs-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
            # Install AWS cli
            - run: npm i angular-cli-ghpages --save-dev
            - run: npx angular-cli-ghpages --dir=docs --repo=https://$Token@github.com/dapplabs/shareit.git --name="circleci" --email=358126+marce1994@users.noreply.github.com --no-silent
            
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
